services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Causal\Theodia\:
    resource: '../Classes/*'
    exclude: '../Classes/Xclass/V11/Backend/Form/FormDataProvider/*'
